vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /uploads/images/services
           upload_destination: '%kernel.project_dir%/public/uploads/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
