name: Deploy to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_ENV: prod
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Configure Symfony environment
        run: |
          echo "APP_ENV=${APP_ENV}" >> .env.local.php
          echo "DATABASE_URL=${DATABASE_URL}" >> .env.local.php
          php bin/console cache:warmup

      - name: Clear Symfony cache
        run: php bin/console cache:clear --env=prod

      - name: Deploy to SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "." # Local directory to upload
          target: ${{ secrets.SFTP_REMOTE_PATH }} # Remote directory
